//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTM.Mgs.Models
{
    using System;
    using System.Collections.Generic;
    using System.Configuration;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.YeuCauNguoiDungs = new HashSet<YeuCauNguoiDung>();
            this.TheLoais = new HashSet<TheLoai>();
            this.NguoiDungs = new HashSet<NguoiDung>();
        }
    
        public int SanPhamId { get; set; }
        public string TenSanPham { get; set; }
        public string MaSanPham { get; set; }
        public string TieuDe { get; set; }
        public string MoTa { get; set; }
        public string Anh { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> TheLoaiId { get; set; }
        public string ChiTiet { get; set; }
        public string NguoiTao { get; set; }
        public string NguoiSua { get; set; }
        public string NguoiXoa { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<bool> DaXoa { get; set; }
        public Nullable<bool> DaPheDuyet { get; set; }
        public Nullable<int> NguoiPheDuyetId { get; set; }
        public Nullable<bool> DaNhapKho { get; set; }
        public Nullable<bool> YeuCauNguoiDung { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual TheLoai TheLoai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeuCauNguoiDung> YeuCauNguoiDungs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TheLoai> TheLoais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguoiDung> NguoiDungs { get; set; }
        public string GetDefautThumbnail()
        {
            if (Anh != null && Anh.Length > 0)
            {
                var arr = Anh.Split(',');
                if (arr.Length > 0)
                {
                    return ConfigurationManager.AppSettings["CloudinaryPrefix"] + arr[0];
                }
            }
            return ConfigurationManager.AppSettings["DefautImage"];
        }
        public string[] GetThumbnails()
        {
            if (Anh != null && Anh.Length > 0)
            {
                var arr = Anh.Split(',');
                if (arr.Length > 0)
                {
                    return arr;
                }
            }
            return new string[0];
        }
        public string[] GetThumbnailsIds()
        {
            var ids = new List<string>();
            var thumbnail = GetThumbnails();
            foreach (var thumd in thumbnail)
            {
                var splitedThumb = thumd.Split('/'); // cat theo "/" 
                if (splitedThumb.Length != 4)
                {
                    continue;
                }
                ids.Add(splitedThumb[3].Split('.')[0]);
            }
            return ids.ToArray();
        }

    }
}
