//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTM.Mgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheLoai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TheLoai()
        {
            this.SanPhams = new HashSet<SanPham>();
            this.YeuCauNguoiDungs = new HashSet<YeuCauNguoiDung>();
        }
    
        public int TheLoadId { get; set; }
        public string TenTheLoai { get; set; }
        public string TieuDe { get; set; }
        public string MoTa { get; set; }
        public string NguoiTao { get; set; }
        public string NguoiSua { get; set; }
        public string NguoiXoa { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<bool> DaXoa { get; set; }
        public Nullable<int> SanPhamId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeuCauNguoiDung> YeuCauNguoiDungs { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
